In [1]:
###########################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd
 
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [2]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
 
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [3]:
###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [4]:
###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)


In [5]:
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1770 - accuracy: 0.9667
Epoch 2/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1771 - accuracy: 0.9667
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1769 - accuracy: 0.9667
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1764 - accuracy: 0.9667
Epoch 5/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1765 - accuracy: 0.9667
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1761 - accuracy: 0.9667
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1765 - accuracy: 0.9667
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1756 - accuracy: 0.9667
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1753 - accuracy: 0.9667
Epoch 10/100
5/5 [==============================] - 0s 0s/step - loss: 0.1756 - accuracy: 0.9667
Epoch 11/100
5/5 [============

5/5 [==============================] - 0s 2ms/step - loss: 0.1627 - accuracy: 0.9667
Epoch 85/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1626 - accuracy: 0.9667
Epoch 86/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1624 - accuracy: 0.9667
Epoch 87/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1627 - accuracy: 0.9733
Epoch 88/100
5/5 [==============================] - 0s 3ms/step - loss: 0.1636 - accuracy: 0.9667
Epoch 89/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1625 - accuracy: 0.9667
Epoch 90/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1619 - accuracy: 0.9667
Epoch 91/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1618 - accuracy: 0.9667
Epoch 92/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1615 - accuracy: 0.9667
Epoch 93/100
5/5 [==============================] - 0s 0s/step - loss: 0.1619 - accuracy: 0.9667
Epoch 94/100
5/5 [================

In [6]:
###########################
# 4. 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9898797e-01 1.0118772e-03 9.8594199e-08]
 [9.9631846e-01 3.6806522e-03 8.2723659e-07]
 [9.9810129e-01 1.8983899e-03 3.1605401e-07]
 [9.9534756e-01 4.6512843e-03 1.2329853e-06]
 [9.9915481e-01 8.4506412e-04 7.5674798e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [8]:
print(model.predict(독립[-5:]))

[[6.1077009e-07 1.2343195e-01 8.7656742e-01]
 [1.7322732e-06 1.9376068e-01 8.0623758e-01]
 [2.9992050e-06 2.3884974e-01 7.6114720e-01]
 [6.5688317e-07 1.2517810e-01 8.7482131e-01]
 [7.7114491e-06 3.1662396e-01 6.8336833e-01]]


In [9]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [10]:
###########################
# weights & bias 출력
print(model.get_weights())

[array([[ 0.7744224 ,  0.21388566, -0.37713403],
       [ 2.79705   ,  0.43334767, -1.0018373 ],
       [-3.3989782 , -0.3666077 ,  0.9460025 ],
       [-4.0162535 , -0.53843665,  2.5266826 ]], dtype=float32), array([ 2.202842 ,  1.4987196, -2.1509168], dtype=float32)]
