In [1]:
###########################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd
 
###########################
# 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
레모네이드.head()
# 종속변수, 독립변수
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [3]:
###########################
# 모델을 만듭니다.
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [4]:
###########################
# 모델을 학습시킵니다. 
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)
 
###########################
# 모델을 이용합니다. 
print(model.predict(독립))
print(model.predict([[15]]))

Epoch 1/10
1/1 [==============================] - 0s 0s/step - loss: 665.8893
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 664.6838
Epoch 3/10
1/1 [==============================] - 0s 0s/step - loss: 663.4793
Epoch 4/10
1/1 [==============================] - 0s 0s/step - loss: 662.2759
Epoch 5/10
1/1 [==============================] - 0s 0s/step - loss: 661.0737
Epoch 6/10
1/1 [==============================] - 0s 0s/step - loss: 659.8725
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 658.6724
Epoch 8/10
1/1 [==============================] - 0s 0s/step - loss: 657.4734
Epoch 9/10
1/1 [==============================] - 0s 0s/step - loss: 656.2756
Epoch 10/10
1/1 [==============================] - 0s 0s/step - loss: 655.0789
[[17.453144]
 [18.275137]
 [19.097128]
 [19.91912 ]
 [20.741114]
 [21.563107]]
[[13.343182]]


In [5]:
model.fit(독립, 종속, epochs=1000, verbose=0)

In [6]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 0s/step - loss: 6.2487
Epoch 2/10
1/1 [==============================] - 0s 0s/step - loss: 6.1406
Epoch 3/10
1/1 [==============================] - 0s 0s/step - loss: 6.0335
Epoch 4/10
1/1 [==============================] - 0s 0s/step - loss: 5.9273
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 5.8222
Epoch 6/10
1/1 [==============================] - 0s 0s/step - loss: 5.7181
Epoch 7/10
1/1 [==============================] - 0s 0s/step - loss: 5.6151
Epoch 8/10
1/1 [==============================] - 0s 0s/step - loss: 5.5130
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 5.4119
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: 5.3119


In [7]:
종속


판매량
0   40
1   42
2   44
3   46
4   48
5   50

In [8]:
print(model.predict([[15]]))

[[29.160519]]


In [9]:
print(model.predict(독립))

[[38.213413]
 [40.02399 ]
 [41.83457 ]
 [43.64515 ]
 [45.455727]
 [47.266308]]


In [10]:
독립

온도
0  20
1  21
2  22
3  23
4  24
5  25

In [11]:
print(model.predict(독립))

[[38.213413]
 [40.02399 ]
 [41.83457 ]
 [43.64515 ]
 [45.455727]
 [47.266308]]


In [12]:
종속

판매량
0   40
1   42
2   44
3   46
4   48
5   50

In [13]:
print(model.predict([[20]]))

[[38.213413]]
